import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'README',
      label: 'Introduction',
    },
    {
      type: 'doc',
      id: 'getting-started',
      label: 'Getting Started',
    },
    {
      type: 'doc',
      id: 'concepts',
      label: 'Core Concepts',
    },
    {
      type: 'doc',
      id: 'token-strategy',
      label: 'Token Strategy',
    },
    {
      type: 'category',
      label: 'Skills',
      link: {type: 'doc', id: 'skills/README'},
      items: [
        {type: 'doc', id: 'skills/DEPENDENCIES', label: 'Dependencies'},
        {
          type: 'category',
          label: 'Product Management',
          link: {type: 'doc', id: 'skills/pm/README'},
          items: [{type: 'autogenerated', dirName: 'skills/pm'}],
        },
        {
          type: 'category',
          label: 'Development',
          link: {type: 'doc', id: 'skills/dev/README'},
          items: [{type: 'autogenerated', dirName: 'skills/dev'}],
        },
        {
          type: 'category',
          label: 'UX',
          link: {type: 'doc', id: 'skills/ux/README'},
          items: [{type: 'autogenerated', dirName: 'skills/ux'}],
        },
        {
          type: 'category',
          label: 'Data & Analytics',
          link: {type: 'doc', id: 'skills/data/README'},
          items: [{type: 'autogenerated', dirName: 'skills/data'}],
        },
        {
          type: 'category',
          label: 'QA',
          items: [{type: 'autogenerated', dirName: 'skills/qa'}],
        },
        {
          type: 'category',
          label: 'Detect & Knowledge',
          link: {type: 'doc', id: 'skills/detect/README'},
          items: [{type: 'autogenerated', dirName: 'skills/detect'}],
        },
        {
          type: 'category',
          label: 'Backend',
          link: {type: 'doc', id: 'skills/backend/README'},
          items: [{type: 'autogenerated', dirName: 'skills/backend'}],
        },
        {
          type: 'category',
          label: 'Frontend',
          link: {type: 'doc', id: 'skills/frontend/README'},
          items: [{type: 'autogenerated', dirName: 'skills/frontend'}],
        },
        {
          type: 'category',
          label: 'Release',
          link: {type: 'doc', id: 'skills/release/README'},
          items: [{type: 'autogenerated', dirName: 'skills/release'}],
        },
        {
          type: 'category',
          label: 'WordPress',
          link: {type: 'doc', id: 'skills/wp/README'},
          items: [{type: 'autogenerated', dirName: 'skills/wp'}],
        },
        {
          type: 'category',
          label: 'Security',
          link: {type: 'doc', id: 'skills/sec/README'},
          items: [{type: 'autogenerated', dirName: 'skills/sec'}],
        },
        {
          type: 'category',
          label: 'DevOps',
          link: {type: 'doc', id: 'skills/devops/README'},
          items: [{type: 'autogenerated', dirName: 'skills/devops'}],
        },
        {
          type: 'category',
          label: 'Core / Internal',
          link: {type: 'doc', id: 'skills/core/README'},
          items: [{type: 'autogenerated', dirName: 'skills/core'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      link: {type: 'doc', id: 'config/README'},
      items: [{type: 'autogenerated', dirName: 'config'}],
    },
    {
      type: 'category',
      label: 'Agents',
      link: {type: 'doc', id: 'agents/README'},
      items: [{type: 'autogenerated', dirName: 'agents'}],
    },
    {
      type: 'category',
      label: 'Hooks',
      link: {type: 'doc', id: 'hooks/README'},
      items: [{type: 'autogenerated', dirName: 'hooks'}],
    },
    {
      type: 'category',
      label: 'Extending',
      link: {type: 'doc', id: 'extending/README'},
      items: [{type: 'autogenerated', dirName: 'extending'}],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
    {
      type: 'category',
      label: 'Roadmap',
      link: {type: 'doc', id: 'roadmap/roadmap'},
      items: [
        {type: 'doc', id: 'roadmap/vision', label: 'Vision'},
        {
          type: 'category',
          label: 'Tasks',
          link: {type: 'doc', id: 'roadmap/tasks/README'},
          items: [{type: 'autogenerated', dirName: 'roadmap/tasks'}],
        },
      ],
    },
    {
      type: 'doc',
      id: 'learning/README',
      label: 'Learning System',
    },
    {
      type: 'category',
      label: 'Research',
      link: {type: 'doc', id: 'research/README'},
      items: [{type: 'autogenerated', dirName: 'research'}],
    },
  ],
};

export default sidebars;
