#!/bin/bash
# jaan.to plugin — first-run bootstrap
# Usage: Runs via SessionStart hook on every session start
# Idempotent — safe to run multiple times

set -euo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-.}"
PLUGIN_DIR="${CLAUDE_PLUGIN_ROOT:-$(dirname "$0")/..}"

# Counters for reporting
CONTEXT_COPIED=0
TEMPLATES_COPIED=0
DOCS_COPIED=0
LEARN_COPIED=0

# 1. Create all necessary directories
mkdir -p "$PROJECT_DIR/.jaan-to/outputs"
mkdir -p "$PROJECT_DIR/.jaan-to/learn"
mkdir -p "$PROJECT_DIR/.jaan-to/context"
mkdir -p "$PROJECT_DIR/.jaan-to/templates"
mkdir -p "$PROJECT_DIR/.jaan-to/docs"
mkdir -p "$PROJECT_DIR/.jaan-to/outputs/research"

# 2. Add to .gitignore if not present
if [ -f "$PROJECT_DIR/.gitignore" ]; then
  if ! grep -q "\.jaan-to" "$PROJECT_DIR/.gitignore" 2>/dev/null; then
    echo ".jaan-to/" >> "$PROJECT_DIR/.gitignore"
  fi
else
  echo ".jaan-to/" > "$PROJECT_DIR/.gitignore"
fi

# 3. Copy context files (skip if exists)
if [ -d "$PLUGIN_DIR/scripts/seeds" ]; then
  for context_file in "$PLUGIN_DIR/scripts/seeds"/*.md; do
    [ -f "$context_file" ] || continue
    filename=$(basename "$context_file")
    dest="$PROJECT_DIR/.jaan-to/context/$filename"
    if [ ! -f "$dest" ]; then
      cp "$context_file" "$dest"
      CONTEXT_COPIED=$((CONTEXT_COPIED + 1))
    fi
  done
fi

# 4. Copy template files (skip if exists)
if [ -d "$PLUGIN_DIR/skills" ]; then
  for template_file in "$PLUGIN_DIR/skills"/*/template.md; do
    [ -f "$template_file" ] || continue
    skill_name=$(basename "$(dirname "$template_file")")
    dest="$PROJECT_DIR/.jaan-to/templates/${skill_name}.template.md"
    if [ ! -f "$dest" ]; then
      cp "$template_file" "$dest"
      TEMPLATES_COPIED=$((TEMPLATES_COPIED + 1))
    fi
  done
fi

# 5. Copy docs needed by skills (skip if exists)
if [ -f "$PLUGIN_DIR/docs/STYLE.md" ]; then
  dest="$PROJECT_DIR/.jaan-to/docs/STYLE.md"
  if [ ! -f "$dest" ]; then
    cp "$PLUGIN_DIR/docs/STYLE.md" "$dest"
    DOCS_COPIED=$((DOCS_COPIED + 1))
  fi
fi

if [ -f "$PLUGIN_DIR/docs/extending/create-skill.md" ]; then
  dest="$PROJECT_DIR/.jaan-to/docs/create-skill.md"
  if [ ! -f "$dest" ]; then
    cp "$PLUGIN_DIR/docs/extending/create-skill.md" "$dest"
    DOCS_COPIED=$((DOCS_COPIED + 1))
  fi
fi

# 6. Create research README if it doesn't exist
research_readme="$PROJECT_DIR/.jaan-to/outputs/research/README.md"
if [ ! -f "$research_readme" ]; then
  cat > "$research_readme" <<'EOF'
# Research Index

This directory contains deep research outputs generated by the `/jaan-to:jaan-research-about` skill.

## Contents

<!-- Research entries will be added here automatically -->
EOF
fi

# 7. Copy LEARN.md seed data (skip if project copy exists)
if [ -d "$PLUGIN_DIR/skills" ]; then
  for skill_learn in "$PLUGIN_DIR/skills"/*/LEARN.md; do
    [ -f "$skill_learn" ] || continue
    skill_name=$(basename "$(dirname "$skill_learn")")
    project_learn="$PROJECT_DIR/.jaan-to/learn/${skill_name}.learn.md"
    if [ ! -f "$project_learn" ]; then
      cp "$skill_learn" "$project_learn"
      LEARN_COPIED=$((LEARN_COPIED + 1))
    fi
  done
fi

# 8. Detect old standalone skills
OLD_SKILLS=()
for pattern in "jaan-to-*" "to-jaan-*"; do
  if ls "$PROJECT_DIR/.claude/skills/"$pattern 1>/dev/null 2>&1; then
    for d in "$PROJECT_DIR/.claude/skills/"$pattern; do
      [ -d "$d" ] && OLD_SKILLS+=("$(basename "$d")")
    done
  fi
done

# 9. Check context files
MISSING_CONTEXT=()
for f in tech.md team.md integrations.md config.md boundaries.md; do
  if [ ! -f "$PLUGIN_DIR/scripts/seeds/$f" ]; then
    MISSING_CONTEXT+=("scripts/seeds/$f")
  fi
done

# 10. Output structured result
if [ ${#OLD_SKILLS[@]} -gt 0 ]; then
  OLD_LIST=$(printf '"%s",' "${OLD_SKILLS[@]}" | sed 's/,$//')
else
  OLD_LIST=""
fi

if [ ${#MISSING_CONTEXT[@]} -gt 0 ]; then
  MISSING_LIST=$(printf '"%s",' "${MISSING_CONTEXT[@]}" | sed 's/,$//')
else
  MISSING_LIST=""
fi

cat <<RESULT
{
  "status": "complete",
  "output_dir": ".jaan-to/outputs",
  "learn_dir": ".jaan-to/learn",
  "context_dir": ".jaan-to/context",
  "templates_dir": ".jaan-to/templates",
  "docs_dir": ".jaan-to/docs",
  "files_copied": {
    "context": ${CONTEXT_COPIED},
    "templates": ${TEMPLATES_COPIED},
    "docs": ${DOCS_COPIED},
    "learn": ${LEARN_COPIED}
  },
  "missing_context": [${MISSING_LIST}],
  "old_standalone_skills": [${OLD_LIST}],
  "migration_needed": $([ ${#OLD_SKILLS[@]} -gt 0 ] && echo "true" || echo "false")
}
RESULT
