#!/bin/bash
# jaan.to plugin — first-run bootstrap
# Usage: Runs via SessionStart hook on every session start
# Idempotent — safe to run multiple times

set -euo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-.}"
PLUGIN_DIR="${CLAUDE_PLUGIN_ROOT:-$(dirname "$0")/..}"

# Load configuration system
if [ -f "${PLUGIN_DIR}/scripts/lib/config-loader.sh" ]; then
  source "${PLUGIN_DIR}/scripts/lib/config-loader.sh"
  load_config
else
  echo "WARNING: config-loader.sh not found, using defaults" >&2
fi

# Resolve paths from config (with fallback defaults)
TEMPLATES_DIR=$(resolve_path "$(get_config 'paths_templates' 'jaan-to/templates')")
LEARN_DIR=$(resolve_path "$(get_config 'paths_learning' 'jaan-to/learn')")
CONTEXT_DIR=$(resolve_path "$(get_config 'paths_context' 'jaan-to/context')")
OUTPUTS_DIR=$(resolve_path "$(get_config 'paths_outputs' 'jaan-to/outputs')")
CONFIG_DIR="jaan-to/config"

# Counters for reporting
CONTEXT_COPIED=0
TEMPLATES_COPIED=0
DOCS_COPIED=0
LEARN_COPIED=0
CONFIG_COPIED=0

# Migration: rename old .jaan-to/ to jaan-to/ if it exists
if [ -d "$PROJECT_DIR/.jaan-to" ] && [ ! -d "$PROJECT_DIR/jaan-to" ]; then
  mv "$PROJECT_DIR/.jaan-to" "$PROJECT_DIR/jaan-to"
fi

# 1. Create all necessary directories (using resolved paths)
mkdir -p "$PROJECT_DIR/$OUTPUTS_DIR"
mkdir -p "$PROJECT_DIR/$LEARN_DIR"
mkdir -p "$PROJECT_DIR/$CONTEXT_DIR"
mkdir -p "$PROJECT_DIR/$TEMPLATES_DIR"
mkdir -p "$PROJECT_DIR/$CONFIG_DIR"
mkdir -p "$PROJECT_DIR/jaan-to/docs"
mkdir -p "$PROJECT_DIR/$OUTPUTS_DIR/research"

# 2. Initialize project config if not exists
if [ ! -f "$PROJECT_DIR/$CONFIG_DIR/settings.yaml" ]; then
  if [ -f "$PLUGIN_DIR/scripts/seeds/settings.yaml" ]; then
    cp "$PLUGIN_DIR/scripts/seeds/settings.yaml" "$PROJECT_DIR/$CONFIG_DIR/settings.yaml"
    CONFIG_COPIED=1
  fi
fi

# 3. Copy context files (skip if exists)
if [ -d "$PLUGIN_DIR/scripts/seeds" ]; then
  for context_file in "$PLUGIN_DIR/scripts/seeds"/*.md; do
    [ -f "$context_file" ] || continue
    filename=$(basename "$context_file")
    dest="$PROJECT_DIR/$CONTEXT_DIR/$filename"
    if [ ! -f "$dest" ]; then
      cp "$context_file" "$dest"
      CONTEXT_COPIED=$((CONTEXT_COPIED + 1))
    fi
  done
fi

# 4. Copy template files (skip if exists)
if [ -d "$PLUGIN_DIR/skills" ]; then
  for template_file in "$PLUGIN_DIR/skills"/*/template.md; do
    [ -f "$template_file" ] || continue
    skill_name=$(basename "$(dirname "$template_file")")
    dest="$PROJECT_DIR/$TEMPLATES_DIR/${skill_name}.template.md"
    if [ ! -f "$dest" ]; then
      cp "$template_file" "$dest"
      TEMPLATES_COPIED=$((TEMPLATES_COPIED + 1))
    fi
  done
fi

# 5. Copy docs needed by skills (skip if exists)
if [ -f "$PLUGIN_DIR/docs/STYLE.md" ]; then
  dest="$PROJECT_DIR/jaan-to/docs/STYLE.md"
  if [ ! -f "$dest" ]; then
    cp "$PLUGIN_DIR/docs/STYLE.md" "$dest"
    DOCS_COPIED=$((DOCS_COPIED + 1))
  fi
fi

if [ -f "$PLUGIN_DIR/docs/extending/create-skill.md" ]; then
  dest="$PROJECT_DIR/jaan-to/docs/create-skill.md"
  if [ ! -f "$dest" ]; then
    cp "$PLUGIN_DIR/docs/extending/create-skill.md" "$dest"
    DOCS_COPIED=$((DOCS_COPIED + 1))
  fi
fi

# 6. Create research README if it doesn't exist
research_readme="$PROJECT_DIR/$OUTPUTS_DIR/research/README.md"
if [ ! -f "$research_readme" ]; then
  cat > "$research_readme" <<'EOF'
# Research Index

This directory contains deep research outputs generated by the `/jaan-to:pm-research-about` skill.

## Contents

<!-- Research entries will be added here automatically -->
EOF
fi

# 7. Copy LEARN.md seed data (skip if project copy exists)
if [ -d "$PLUGIN_DIR/skills" ]; then
  for skill_learn in "$PLUGIN_DIR/skills"/*/LEARN.md; do
    [ -f "$skill_learn" ] || continue
    skill_name=$(basename "$(dirname "$skill_learn")")
    project_learn="$PROJECT_DIR/$LEARN_DIR/${skill_name}.learn.md"
    if [ ! -f "$project_learn" ]; then
      cp "$skill_learn" "$project_learn"
      LEARN_COPIED=$((LEARN_COPIED + 1))
    fi
  done
fi

# 8. Detect old standalone skills (with old naming convention)
OLD_SKILLS=()
# Old naming: pm-prd-write, data-gtm-datalayer, jaan-docs-*, jaan-skill-*, etc.
OLD_PATTERNS=(
  "pm-prd-write" "data-gtm-datalayer"
  "jaan-docs-create" "jaan-docs-update"
  "jaan-learn-add" "jaan-research-about" "jaan-research-add"
  "research-about" "research-add"
  "jaan-roadmap-add" "jaan-skill-create" "jaan-skill-update"
  # v3.15.2 → v3.16.0 rename: old prefixed names
  "jaan-to-pm-prd-write" "jaan-to-pm-story-write" "jaan-to-pm-research-about"
  "jaan-to-dev-fe-design" "jaan-to-dev-fe-task-breakdown" "jaan-to-dev-be-task-breakdown"
  "jaan-to-dev-stack-detect" "jaan-to-qa-test-cases"
  "jaan-to-ux-research-synthesize" "jaan-to-ux-microcopy-write" "jaan-to-ux-heatmap-analyze"
  "jaan-to-data-gtm-datalayer"
  "to-jaan-docs-create" "to-jaan-docs-update" "to-jaan-learn-add"
  "to-jaan-roadmap-add" "to-jaan-roadmap-update"
  "to-jaan-skill-create" "to-jaan-skill-update"
)
for pattern in "${OLD_PATTERNS[@]}"; do
  if [ -d "$PROJECT_DIR/.claude/skills/$pattern" ]; then
    OLD_SKILLS+=("$pattern")
  fi
done

# 9. Check context files
MISSING_CONTEXT=()
for f in tech.md team.md integrations.md config.md boundaries.md; do
  if [ ! -f "$PLUGIN_DIR/scripts/seeds/$f" ]; then
    MISSING_CONTEXT+=("scripts/seeds/$f")
  fi
done

# 10. Check if stack detection should be suggested (context files still have placeholders)
SUGGEST_STACK_DETECT="false"
if [ -f "$PROJECT_DIR/$CONTEXT_DIR/tech.md" ]; then
  if grep -q '{project-name}' "$PROJECT_DIR/$CONTEXT_DIR/tech.md" 2>/dev/null; then
    SUGGEST_STACK_DETECT="true"
  fi
fi

# 11. Output structured result
if [ ${#OLD_SKILLS[@]} -gt 0 ]; then
  OLD_LIST=$(printf '"%s",' "${OLD_SKILLS[@]}" | sed 's/,$//')
else
  OLD_LIST=""
fi

if [ ${#MISSING_CONTEXT[@]} -gt 0 ]; then
  MISSING_LIST=$(printf '"%s",' "${MISSING_CONTEXT[@]}" | sed 's/,$//')
else
  MISSING_LIST=""
fi

cat <<RESULT
{
  "status": "complete",
  "config_loaded": true,
  "output_dir": "${OUTPUTS_DIR}",
  "learn_dir": "${LEARN_DIR}",
  "context_dir": "${CONTEXT_DIR}",
  "templates_dir": "${TEMPLATES_DIR}",
  "config_dir": "${CONFIG_DIR}",
  "paths_customized": $([ "$TEMPLATES_DIR" != "jaan-to/templates" ] && echo "true" || echo "false"),
  "files_copied": {
    "config": ${CONFIG_COPIED},
    "context": ${CONTEXT_COPIED},
    "templates": ${TEMPLATES_COPIED},
    "docs": ${DOCS_COPIED},
    "learn": ${LEARN_COPIED}
  },
  "missing_context": [${MISSING_LIST}],
  "old_standalone_skills": [${OLD_LIST}],
  "migration_needed": $([ ${#OLD_SKILLS[@]} -gt 0 ] && echo "true" || echo "false"),
  "suggest_stack_detect": ${SUGGEST_STACK_DETECT}
}
RESULT
